name: build

on:
  # 当有pr合到master和release分支时，开始构建
  pull_request:
    branches:
      - master
      - release-*

  # 当有直接推到master分支时，开始构建。一般不允许直接提交到master分支
  push:
    branches:
      - master 

jobs:
  buildbuild:
    name: Install
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12


      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build Gaea
        run: make build

      # - name: Install And Check
      #   working-directory: ${{ env.working-directory }}
      #   run: |
      #     sh install.sh
      #     source ~/.profile
      #     which tiup || (echo "no tiup found" && exit 1)
      #     cp ./bin/tiup $(which tiup)
      #     ! tiup update --self | grep -i "WARN: adding root certificate"
      #     tiup --version
  # local_install:
  #   name: Local Install
  #   runs-on: ubuntu-latest
  #   env:
  #     working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
  #   steps:
  #     - name: Check out code into the Go module directory
  #       uses: actions/checkout@v2
  #       with:
  #         ref: ${{ github.event.pull_request.head.sha }}
  #         path: go/src/github.com/${{ github.repository }}
  #     - name: Build TiUP
  #       working-directory: ${{ env.working-directory }}
  #       run: make build
  #     - name: Setup TiUP
  #       run: |
  #         mkdir -p ~/.tiup/bin
  #         curl https://tiup-mirrors.pingcap.com/root.json -o ~/.tiup/bin/root.json
  #     - name: Clone Mirror
  #       working-directory: ${{ env.working-directory }}
  #       run: ./bin/tiup mirror clone test-mirror
  #     - name: Local Install And Check
  #       working-directory: ${{ env.working-directory }}/test-mirror
  #       run: |
  #         sh local_install.sh
  #         source ~/.profile
  #         which tiup || (echo "no tiup found" && exit 1)
  #         cp ../bin/tiup $(which tiup)
  #         ! tiup update --self | grep -i "WARN: adding root certificate"
  #         tiup --version
